/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AllInfoLinks } from './allInfoLinks';

export class AllInfo {
    /**
    * Connect version
    */
    'version': string;
    'links': AllInfoLinks;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "AllInfoLinks"
        }    ];

    static getAttributeTypeMap() {
        return AllInfo.attributeTypeMap;
    }
}

