/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChainListData } from './chainListData';

/**
* Represents a list of Factom entries that have been or will be saved to the blockchain.
*/
export class ChainList {
    /**
    * An array that contains the chains on this page.
    */
    'data': Array<ChainListData>;
    /**
    * The page offset. (Current page -1)
    */
    'offset': string;
    /**
    * The maximum number of chains per page.
    */
    'limit': string;
    /**
    * The total number of chains seen.
    */
    'count': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ChainListData>"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChainList.attributeTypeMap;
    }
}

