/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Represents a list of Factom chains that have been or will be saved to the blockchain.
*/
export class ChainShort {
    /**
    * This is the unique identifier created for each chain.
    */
    'chainId': string;
    /**
    * The SHA256 Hash of the chain's first entry.
    */
    'entryHash': string;
    /**
    * The immutability stage that this chain has reached.
    */
    'stage': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "string"
        },
        {
            "name": "entryHash",
            "baseName": "entry_hash",
            "type": "string"
        },
        {
            "name": "stage",
            "baseName": "stage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChainShort.attributeTypeMap;
    }
}

