/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* Used to create a new chain on Connect.
*/
export class ChainCreate {
    /**
    * Tags that can be used to identify your chain. You can search for records that contain a particular external_id using Connect. You must send External IDs in Base64 format.
    */
    'externalIds': Array<string>;
    /**
    * This is the data that will make up the first entry in your new chain. It is customary to use this space to describe the entries that are to follow in the chain. You must send the content field in Base64 format.
    */
    'content': string;
    /**
    * The URL where you would like to receive the callback from Connect. If this is not specified, callbacks will not activate.
    */
    'callbackUrl'?: string;
    /**
    * The stages that you would like to trigger a callback from Connect. This list can include any or all of the three stages: `replicated`, `factom`, and `anchored`. If callbacks are activated and this field is not sent, it will default to `factom` and `anchored`
    */
    'callbackStages'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalIds",
            "baseName": "external_ids",
            "type": "Array<string>"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "callbackUrl",
            "baseName": "callback_url",
            "type": "string"
        },
        {
            "name": "callbackStages",
            "baseName": "callback_stages",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ChainCreate.attributeTypeMap;
    }
}

