/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class ChainListData {
    /**
    * The ID for this chain on the Factom blockchain.
    */
    'chainId': string;
    /**
    * The external IDs attached to this chain on the Factom blockchain.
    */
    'externalIds': Array<string>;
    /**
    * An API link to retrieve all information about this chain.
    */
    'href': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "string"
        },
        {
            "name": "externalIds",
            "baseName": "external_ids",
            "type": "Array<string>"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChainListData.attributeTypeMap;
    }
}

