/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChainData } from './chainData';

/**
* Represents a list of Factom entries that have been or will be saved to the blockchain.
*/
export class Chain {
    'data': ChainData;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "ChainData"
        }    ];

    static getAttributeTypeMap() {
        return Chain.attributeTypeMap;
    }
}

