/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ChainDataEntries } from './chainDataEntries';

export class ChainData {
    /**
    * This is the unique identifier created for each chain.
    */
    'chainId': string;
    /**
    * Tags that have been used to identify this entry.
    */
    'externalIds': Array<string>;
    /**
    * The immutability stage that this chain has reached.
    */
    'stage': string;
    'entries': ChainDataEntries;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chainId",
            "baseName": "chain_id",
            "type": "string"
        },
        {
            "name": "externalIds",
            "baseName": "external_ids",
            "type": "Array<string>"
        },
        {
            "name": "stage",
            "baseName": "stage",
            "type": "string"
        },
        {
            "name": "entries",
            "baseName": "entries",
            "type": "ChainDataEntries"
        }    ];

    static getAttributeTypeMap() {
        return ChainData.attributeTypeMap;
    }
}

