/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class EntryShort {
    /**
    * The SHA256 Hash of the entry you just created. You can use this hash to referece this entry in the future.
    */
    'entryHash'?: string;
    /**
    * The current immutability stage of the new entry. Only returned if callbacks are enabled.
    */
    'stage'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entryHash",
            "baseName": "entry_hash",
            "type": "string"
        },
        {
            "name": "stage",
            "baseName": "stage",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntryShort.attributeTypeMap;
    }
}

