/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntrySearchResponseData } from './entrySearchResponseData';

export class EntrySearchResponse {
    /**
    * An array of entries that match your search criterion.
    */
    'data': Array<EntrySearchResponseData>;
    /**
    * The page offset. (Current page -1)
    */
    'offset': string;
    /**
    * The maximum number of entries per page.
    */
    'limit': string;
    /**
    * The total number of entries seen.
    */
    'count': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<EntrySearchResponseData>"
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "string"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntrySearchResponse.attributeTypeMap;
    }
}

