/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class EntryDataEblock {
    /**
    * The Key Merkle Root for this entry block.
    */
    'keymr'?: string;
    /**
    * An API link to retrieve all information about this entry block.
    */
    'href'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "keymr",
            "baseName": "keymr",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntryDataEblock.attributeTypeMap;
    }
}

