/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntryDataEblock } from './entryDataEblock';
import { EntryLinkChain } from './entryLinkChain';

export class EntryData {
    /**
    * The SHA256 Hash of this entry.
    */
    'entryHash'?: string;
    'chain'?: EntryLinkChain;
    /**
    * The time when this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
    */
    'createdAt'?: string;
    /**
    * Tags that can be used to identify your entry. You can search for records that contain a particular external_id using Connect. External IDs are returned in Base64.
    */
    'externalIds'?: Array<string>;
    /**
    * This is the data that is stored by the entry. Content will be sent in Base64 format.
    */
    'content'?: string;
    /**
    * The level of immutability that this entry has reached.
    */
    'stage'?: string;
    'eblock'?: EntryDataEblock;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entryHash",
            "baseName": "entry_hash",
            "type": "string"
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "EntryLinkChain"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "externalIds",
            "baseName": "external_ids",
            "type": "Array<string>"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "stage",
            "baseName": "stage",
            "type": "string"
        },
        {
            "name": "eblock",
            "baseName": "eblock",
            "type": "EntryDataEblock"
        }    ];

    static getAttributeTypeMap() {
        return EntryData.attributeTypeMap;
    }
}

