/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EntryLinkChain } from './entryLinkChain';

/**
* An object that contains the Entry Hash (ID) and a URL for the entry.
*/
export class EntryLink {
    /**
    * The SHA256 Hash of this entry.
    */
    'entryHash': string;
    'chain': EntryLinkChain;
    /**
    * The time at which this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
    */
    'createdAt': string;
    /**
    * An API link to retrieve all information about this entry.
    */
    'href': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "entryHash",
            "baseName": "entry_hash",
            "type": "string"
        },
        {
            "name": "chain",
            "baseName": "chain",
            "type": "EntryLinkChain"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntryLink.attributeTypeMap;
    }
}

