/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
* The external IDs of the chains or entries you want to retrieve. You must enter these External IDs in Base64 format.
*/
export class SearchBody {
    /**
    * A list of external IDs.
    */
    'externalIds': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "externalIds",
            "baseName": "external_ids",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return SearchBody.attributeTypeMap;
    }
}

