/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AllInfoLinks'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AllInfoLinks'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.AllInfo = factory(root.HarmonyConnectClient.ApiClient, root.HarmonyConnectClient.AllInfoLinks);
  }
}(this, function(ApiClient, AllInfoLinks) {
  'use strict';



  /**
   * The AllInfo model module.
   * @module model/AllInfo
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>AllInfo</code>.
   * @alias module:model/AllInfo
   * @class
   * @param version {String} Connect version
   * @param links {module:model/AllInfoLinks} 
   */
  var exports = function(version, links) {
    var _this = this;

    _this['version'] = version;
    _this['links'] = links;
  };

  /**
   * Constructs a <code>AllInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AllInfo} obj Optional instance to populate.
   * @return {module:model/AllInfo} The populated <code>AllInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('version')) {
        obj['version'] = ApiClient.convertToType(data['version'], 'String');
      }
      if (data.hasOwnProperty('links')) {
        obj['links'] = AllInfoLinks.constructFromObject(data['links']);
      }
    }
    return obj;
  }

  /**
   * Connect version
   * @member {String} version
   */
  exports.prototype['version'] = undefined;
  /**
   * @member {module:model/AllInfoLinks} links
   */
  exports.prototype['links'] = undefined;



  return exports;
}));


