/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ChainListData'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ChainListData'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.ChainList = factory(root.HarmonyConnectClient.ApiClient, root.HarmonyConnectClient.ChainListData);
  }
}(this, function(ApiClient, ChainListData) {
  'use strict';



  /**
   * The ChainList model module.
   * @module model/ChainList
   * @version 1.0.7
   */

  /**
   * Constructs a new <code>ChainList</code>.
   * Represents a list of Factom entries that have been or will be saved to the blockchain.
   * @alias module:model/ChainList
   * @class
   * @param data {Array.<module:model/ChainListData>} An array that contains the chains on this page.
   * @param offset {Number} The index of the first chain returned from the total set (Starting from 0).
   * @param limit {Number} The number of chains returned.
   * @param count {Number} The total number of chains seen.
   */
  var exports = function(data, offset, limit, count) {
    var _this = this;

    _this['data'] = data;
    _this['offset'] = offset;
    _this['limit'] = limit;
    _this['count'] = count;
  };

  /**
   * Constructs a <code>ChainList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChainList} obj Optional instance to populate.
   * @return {module:model/ChainList} The populated <code>ChainList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('data')) {
        obj['data'] = ApiClient.convertToType(data['data'], [ChainListData]);
      }
      if (data.hasOwnProperty('offset')) {
        obj['offset'] = ApiClient.convertToType(data['offset'], 'Number');
      }
      if (data.hasOwnProperty('limit')) {
        obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
      }
      if (data.hasOwnProperty('count')) {
        obj['count'] = ApiClient.convertToType(data['count'], 'Number');
      }
    }
    return obj;
  }

  /**
   * An array that contains the chains on this page.
   * @member {Array.<module:model/ChainListData>} data
   */
  exports.prototype['data'] = undefined;
  /**
   * The index of the first chain returned from the total set (Starting from 0).
   * @member {Number} offset
   */
  exports.prototype['offset'] = undefined;
  /**
   * The number of chains returned.
   * @member {Number} limit
   */
  exports.prototype['limit'] = undefined;
  /**
   * The total number of chains seen.
   * @member {Number} count
   */
  exports.prototype['count'] = undefined;



  return exports;
}));


