/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.ChainShort = factory(root.HarmonyConnectClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ChainShort model module.
   * @module model/ChainShort
   * @version 1.0.7
   */

  /**
   * Constructs a new <code>ChainShort</code>.
   * Represents a list of Factom chains that have been or will be saved to the blockchain.
   * @alias module:model/ChainShort
   * @class
   * @param chainId {String} This is the unique identifier created for each chain.
   * @param entryHash {String} The SHA256 Hash of the chain's first entry.
   * @param stage {String} The immutability stage that this chain has reached.
   */
  var exports = function(chainId, entryHash, stage) {
    var _this = this;

    _this['chain_id'] = chainId;
    _this['entry_hash'] = entryHash;
    _this['stage'] = stage;
  };

  /**
   * Constructs a <code>ChainShort</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ChainShort} obj Optional instance to populate.
   * @return {module:model/ChainShort} The populated <code>ChainShort</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('chain_id')) {
        obj['chain_id'] = ApiClient.convertToType(data['chain_id'], 'String');
      }
      if (data.hasOwnProperty('entry_hash')) {
        obj['entry_hash'] = ApiClient.convertToType(data['entry_hash'], 'String');
      }
      if (data.hasOwnProperty('stage')) {
        obj['stage'] = ApiClient.convertToType(data['stage'], 'String');
      }
    }
    return obj;
  }

  /**
   * This is the unique identifier created for each chain.
   * @member {String} chain_id
   */
  exports.prototype['chain_id'] = undefined;
  /**
   * The SHA256 Hash of the chain's first entry.
   * @member {String} entry_hash
   */
  exports.prototype['entry_hash'] = undefined;
  /**
   * The immutability stage that this chain has reached.
   * @member {String} stage
   */
  exports.prototype['stage'] = undefined;



  return exports;
}));


