/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntryListChain'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntryListChain'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.EntryListData = factory(root.HarmonyConnectClient.ApiClient, root.HarmonyConnectClient.EntryListChain);
  }
}(this, function(ApiClient, EntryListChain) {
  'use strict';



  /**
   * The EntryListData model module.
   * @module model/EntryListData
   * @version 1.0.7
   */

  /**
   * Constructs a new <code>EntryListData</code>.
   * @alias module:model/EntryListData
   * @class
   * @param entryHash {String} The SHA256 Hash of this entry.
   * @param chain {module:model/EntryListChain} 
   * @param href {String} An API link to retrieve all information about this entry.
   */
  var exports = function(entryHash, chain, href) {
    var _this = this;

    _this['entry_hash'] = entryHash;
    _this['chain'] = chain;
    _this['href'] = href;
  };

  /**
   * Constructs a <code>EntryListData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EntryListData} obj Optional instance to populate.
   * @return {module:model/EntryListData} The populated <code>EntryListData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('entry_hash')) {
        obj['entry_hash'] = ApiClient.convertToType(data['entry_hash'], 'String');
      }
      if (data.hasOwnProperty('chain')) {
        obj['chain'] = EntryListChain.constructFromObject(data['chain']);
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('href')) {
        obj['href'] = ApiClient.convertToType(data['href'], 'String');
      }
    }
    return obj;
  }

  /**
   * The SHA256 Hash of this entry.
   * @member {String} entry_hash
   */
  exports.prototype['entry_hash'] = undefined;
  /**
   * @member {module:model/EntryListChain} chain
   */
  exports.prototype['chain'] = undefined;
  /**
   * The time at which this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ss.ssssssZ`
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * An API link to retrieve all information about this entry.
   * @member {String} href
   */
  exports.prototype['href'] = undefined;



  return exports;
}));


