/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EntryDataEblock', 'model/EntryLinkChain'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./EntryDataEblock'), require('./EntryLinkChain'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.EntryData = factory(root.HarmonyConnectClient.ApiClient, root.HarmonyConnectClient.EntryDataEblock, root.HarmonyConnectClient.EntryLinkChain);
  }
}(this, function(ApiClient, EntryDataEblock, EntryLinkChain) {
  'use strict';



  /**
   * The EntryData model module.
   * @module model/EntryData
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>EntryData</code>.
   * @alias module:model/EntryData
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>EntryData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EntryData} obj Optional instance to populate.
   * @return {module:model/EntryData} The populated <code>EntryData</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('entry_hash')) {
        obj['entry_hash'] = ApiClient.convertToType(data['entry_hash'], 'String');
      }
      if (data.hasOwnProperty('chain')) {
        obj['chain'] = EntryLinkChain.constructFromObject(data['chain']);
      }
      if (data.hasOwnProperty('created_at')) {
        obj['created_at'] = ApiClient.convertToType(data['created_at'], 'String');
      }
      if (data.hasOwnProperty('external_ids')) {
        obj['external_ids'] = ApiClient.convertToType(data['external_ids'], ['String']);
      }
      if (data.hasOwnProperty('content')) {
        obj['content'] = ApiClient.convertToType(data['content'], 'String');
      }
      if (data.hasOwnProperty('stage')) {
        obj['stage'] = ApiClient.convertToType(data['stage'], 'String');
      }
      if (data.hasOwnProperty('eblock')) {
        obj['eblock'] = EntryDataEblock.constructFromObject(data['eblock']);
      }
    }
    return obj;
  }

  /**
   * The SHA256 Hash of this entry.
   * @member {String} entry_hash
   */
  exports.prototype['entry_hash'] = undefined;
  /**
   * @member {module:model/EntryLinkChain} chain
   */
  exports.prototype['chain'] = undefined;
  /**
   * The time when this entry was created. Sent in [ISO 8601 Format](https://en.wikipedia.org/wiki/ISO_8601). For example: `YYYY-MM-DDThh:mm:ssZ`
   * @member {String} created_at
   */
  exports.prototype['created_at'] = undefined;
  /**
   * Tags that can be used to identify your entry. You can search for records that contain a particular external_id using Connect. External IDs are returned in Base64.
   * @member {Array.<String>} external_ids
   */
  exports.prototype['external_ids'] = undefined;
  /**
   * This is the data that is stored by the entry. Content will be sent in Base64 format.
   * @member {String} content
   */
  exports.prototype['content'] = undefined;
  /**
   * The level of immutability that this entry has reached.
   * @member {String} stage
   */
  exports.prototype['stage'] = undefined;
  /**
   * @member {module:model/EntryDataEblock} eblock
   */
  exports.prototype['eblock'] = undefined;



  return exports;
}));


