/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.EntryShort = factory(root.HarmonyConnectClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The EntryShort model module.
   * @module model/EntryShort
   * @version 1.0.7
   */

  /**
   * Constructs a new <code>EntryShort</code>.
   * @alias module:model/EntryShort
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>EntryShort</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EntryShort} obj Optional instance to populate.
   * @return {module:model/EntryShort} The populated <code>EntryShort</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('entry_hash')) {
        obj['entry_hash'] = ApiClient.convertToType(data['entry_hash'], 'String');
      }
      if (data.hasOwnProperty('stage')) {
        obj['stage'] = ApiClient.convertToType(data['stage'], 'String');
      }
    }
    return obj;
  }

  /**
   * The SHA256 Hash of the entry you just created. You can use this hash to referece this entry in the future.
   * @member {String} entry_hash
   */
  exports.prototype['entry_hash'] = undefined;
  /**
   * The current immutability stage of the new entry.
   * @member {String} stage
   */
  exports.prototype['stage'] = undefined;



  return exports;
}));


