/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.SearchBody = factory(root.HarmonyConnectClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The SearchBody model module.
   * @module model/SearchBody
   * @version 1.0.7
   */

  /**
   * Constructs a new <code>SearchBody</code>.
   * The external IDs of the chains or entries you want to retrieve. You must enter these External IDs in Base64 format.
   * @alias module:model/SearchBody
   * @class
   * @param externalIds {Array.<String>} A list of external IDs.
   */
  var exports = function(externalIds) {
    var _this = this;

    _this['external_ids'] = externalIds;
  };

  /**
   * Constructs a <code>SearchBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchBody} obj Optional instance to populate.
   * @return {module:model/SearchBody} The populated <code>SearchBody</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('external_ids')) {
        obj['external_ids'] = ApiClient.convertToType(data['external_ids'], ['String']);
      }
    }
    return obj;
  }

  /**
   * A list of external IDs.
   * @member {Array.<String>} external_ids
   */
  exports.prototype['external_ids'] = undefined;



  return exports;
}));


