/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AllInfo'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/AllInfo'));
  } else {
    // Browser globals (root is window)
    if (!root.HarmonyConnectClient) {
      root.HarmonyConnectClient = {};
    }
    root.HarmonyConnectClient.InfoApi = factory(root.HarmonyConnectClient.ApiClient, root.HarmonyConnectClient.AllInfo);
  }
}(this, function(ApiClient, AllInfo) {
  'use strict';

  /**
   * Info service.
   * @module api/InfoApi
   * @version 1.0.1
   */

  /**
   * Constructs a new InfoApi. 
   * @alias module:api/InfoApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getApiInfo operation.
     * @callback module:api/InfoApi~getApiInfoCallback
     * @param {String} error Error message, if any.
     * @param {module:model/AllInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * API Info
     * Request general information about the Connect API such as the version and available endpoints.
     * @param {module:api/InfoApi~getApiInfoCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/AllInfo}
     */
    this.getApiInfo = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['AppId', 'AppKey'];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = AllInfo;

      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
