/**
 * Harmony Connect
 * An easy to use API that helps you access the Factom blockchain.
 *
 * OpenAPI spec version: 1.0.17
 * Contact: harmony-support@factom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.3.4
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HarmonyConnectClient);
  }
}(this, function(expect, HarmonyConnectClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HarmonyConnectClient.ChainData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChainData', function() {
    it('should create an instance of ChainData', function() {
      // uncomment below and update the code to test ChainData
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be.a(HarmonyConnectClient.ChainData);
    });

    it('should have the property chainId (base name: "chain_id")', function() {
      // uncomment below and update the code to test the property chainId
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

    it('should have the property content (base name: "content")', function() {
      // uncomment below and update the code to test the property content
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

    it('should have the property externalIds (base name: "external_ids")', function() {
      // uncomment below and update the code to test the property externalIds
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

    it('should have the property stage (base name: "stage")', function() {
      // uncomment below and update the code to test the property stage
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

    it('should have the property entries (base name: "entries")', function() {
      // uncomment below and update the code to test the property entries
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

    it('should have the property eblock (base name: "eblock")', function() {
      // uncomment below and update the code to test the property eblock
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

    it('should have the property dblock (base name: "dblock")', function() {
      // uncomment below and update the code to test the property dblock
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new HarmonyConnectClient.ChainData();
      //expect(instance).to.be();
    });

  });

}));
